/** Bogotá y municipios aledaños — espejo del seed backend. */
export const CIUDADES_BOGOTA_AREA = [
  'Bogotá',
  'Soacha',
  'Chía',
  'Cajicá',
  'Zipaquirá',
  'Facatativá',
  'Funza',
  'Madrid',
  'Mosquera',
  'Cota',
  'La Calera',
  'Sopó',
  'Tocancipá',
  'Gachancipá',
  'Sibaté',
  'Bojacá',
  'El Rosal',
  'Subachoque',
  'Tenjo',
  'Tabio',
  'Nemocón',
  'Cogua',
] as const;
